# Generated by Django 2.1.1 on 2018-09-12 14:31

from django.db import migrations, models
import tracks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ballad', 'Ballad'), ('classic', 'Classic Rock'), ('pop', 'Pop Rock'), ('progressive', 'Progressive Rock'), ('symphonic', 'Symphonic Rock')], max_length=128)),
            ],
        ),
    ]
