# Generated by Django 2.1.1 on 2018-09-12 14:34

from django.db import migrations, models
import django.db.models.deletion
import tracks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracks.Genre'),
        ),
    ]
