sogo: main.cpp Sogo.cpp SogoBoard.cpp
	g++ --std=c++14 -Wall -g -O3 -o sogo main.cpp Sogo.cpp SogoBoard.cpp 

sogoboard: main.cpp SogoBoard.cpp
	g++ --std=c++14 -Wall -g -O3 -o sogo main.cpp SogoBoard.cpp 

clean: 
	$(RM) sogo
